name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up LaTeX
      uses: docker://danteev/texlive:latest
    - name: Build LaTeX document
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error -file-line-error -synctex=1 Progetto.tex