name: Compile LaTeX documents

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up TeX Live
        uses: DanySK/setup-texlive-action@0.1.1
        with:
          scheme: basic

       
      - name: Check out code
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        run: |
          latexmk -pdf -interaction=nonstopmode -synctex=1 -file-line-error src/Progetto.tex  


      - name: Upload PDF 
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: Progetto.pdf

      
