name: LaTeX Check

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up LaTeX
      uses: docker://danteev/texlive:latest
    - name: Install lacheck
      run: sudo apt-get update && sudo apt-get install -y lacheck
    - name: Check LaTeX structure
      run: |
        lacheck src/Progetto.tex
        chktex -n 6 src/Progetto.tex